// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'models.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Post _$PostFromJson(Map<String, dynamic> json) => Post(
      id: (json['id'] as num).toInt(),
      date: json['date'] as String?,
      dateGmt: json['dateGmt'] as String?,
      guid: json['guid'] as Map<String, dynamic>?,
      modified: json['modified'] as String?,
      modifiedGmt: json['modifiedGmt'] as String?,
      slug: json['slug'] as String?,
      status: json['status'] as String?,
      type: json['type'] as String?,
      link: json['link'] as String?,
      title: json['title'] as Map<String, dynamic>?,
      content: json['content'] as Map<String, dynamic>?,
      excerpt: json['excerpt'] as Map<String, dynamic>?,
      author: (json['author'] as num?)?.toInt(),
      featuredMedia: (json['featuredMedia'] as num?)?.toInt(),
      commentStatus: json['commentStatus'] as String?,
      pingStatus: json['pingStatus'] as String?,
      sticky: json['sticky'] as bool?,
      template: json['template'] as String?,
      format: json['format'] as String?,
      categories: json['categories'] as List<dynamic>?,
      tags: json['tags'] as List<dynamic>?,
      meta: json['meta'] as Map<String, dynamic>?,
      links: json['links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$PostToJson(Post instance) => <String, dynamic>{
      'id': instance.id,
      'date': instance.date,
      'dateGmt': instance.dateGmt,
      'guid': instance.guid,
      'modified': instance.modified,
      'modifiedGmt': instance.modifiedGmt,
      'slug': instance.slug,
      'status': instance.status,
      'type': instance.type,
      'link': instance.link,
      'title': instance.title,
      'content': instance.content,
      'excerpt': instance.excerpt,
      'author': instance.author,
      'featuredMedia': instance.featuredMedia,
      'commentStatus': instance.commentStatus,
      'pingStatus': instance.pingStatus,
      'sticky': instance.sticky,
      'template': instance.template,
      'format': instance.format,
      'categories': instance.categories,
      'tags': instance.tags,
      'meta': instance.meta,
      'links': instance.links,
    };

Page _$PageFromJson(Map<String, dynamic> json) => Page(
      id: (json['id'] as num).toInt(),
      date: json['date'] as String?,
      dateGmt: json['dateGmt'] as String?,
      guid: json['guid'] as Map<String, dynamic>?,
      modified: json['modified'] as String?,
      modifiedGmt: json['modifiedGmt'] as String?,
      slug: json['slug'] as String?,
      status: json['status'] as String?,
      type: json['type'] as String?,
      link: json['link'] as String?,
      title: json['title'] as Map<String, dynamic>?,
      content: json['content'] as Map<String, dynamic>?,
      excerpt: json['excerpt'] as Map<String, dynamic>?,
      author: (json['author'] as num?)?.toInt(),
      featuredMedia: (json['featuredMedia'] as num?)?.toInt(),
      parent: (json['parent'] as num?)?.toInt(),
      menuOrder: (json['menuOrder'] as num?)?.toInt(),
      commentStatus: json['commentStatus'] as String?,
      pingStatus: json['pingStatus'] as String?,
      template: json['template'] as String?,
      meta: json['meta'] as Map<String, dynamic>?,
      links: json['links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$PageToJson(Page instance) => <String, dynamic>{
      'id': instance.id,
      'date': instance.date,
      'dateGmt': instance.dateGmt,
      'guid': instance.guid,
      'modified': instance.modified,
      'modifiedGmt': instance.modifiedGmt,
      'slug': instance.slug,
      'status': instance.status,
      'type': instance.type,
      'link': instance.link,
      'title': instance.title,
      'content': instance.content,
      'excerpt': instance.excerpt,
      'author': instance.author,
      'featuredMedia': instance.featuredMedia,
      'parent': instance.parent,
      'menuOrder': instance.menuOrder,
      'commentStatus': instance.commentStatus,
      'pingStatus': instance.pingStatus,
      'template': instance.template,
      'meta': instance.meta,
      'links': instance.links,
    };

User _$UserFromJson(Map<String, dynamic> json) => User(
      id: (json['id'] as num).toInt(),
      username: json['username'] as String?,
      name: json['name'] as String?,
      firstName: json['firstName'] as String?,
      lastName: json['lastName'] as String?,
      email: json['email'] as String?,
      url: json['url'] as String?,
      description: json['description'] as String?,
      link: json['link'] as String?,
      locale: json['locale'] as String?,
      nickname: json['nickname'] as String?,
      slug: json['slug'] as String?,
      roles: json['roles'] as List<dynamic>?,
      registeredDate: json['registeredDate'] as String?,
      capabilities: json['capabilities'] as Map<String, dynamic>?,
      extraCapabilities: json['extraCapabilities'] as Map<String, dynamic>?,
      meta: json['meta'] as List<dynamic>?,
      avatarUrls: json['avatar_urls'] as Map<String, dynamic>?,
      links: json['_links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'username': instance.username,
      'name': instance.name,
      'firstName': instance.firstName,
      'lastName': instance.lastName,
      'email': instance.email,
      'url': instance.url,
      'description': instance.description,
      'link': instance.link,
      'locale': instance.locale,
      'nickname': instance.nickname,
      'slug': instance.slug,
      'roles': instance.roles,
      'registeredDate': instance.registeredDate,
      'capabilities': instance.capabilities,
      'extraCapabilities': instance.extraCapabilities,
      'meta': instance.meta,
      'avatar_urls': instance.avatarUrls,
      '_links': instance.links,
    };

Category _$CategoryFromJson(Map<String, dynamic> json) => Category(
      id: (json['id'] as num).toInt(),
      count: (json['count'] as num?)?.toInt(),
      description: json['description'] as String?,
      link: json['link'] as String?,
      name: json['name'] as String?,
      slug: json['slug'] as String?,
      taxonomy: json['taxonomy'] as String?,
      parent: (json['parent'] as num?)?.toInt(),
      meta: json['meta'] as List<dynamic>?,
      links: json['links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$CategoryToJson(Category instance) => <String, dynamic>{
      'id': instance.id,
      'count': instance.count,
      'description': instance.description,
      'link': instance.link,
      'name': instance.name,
      'slug': instance.slug,
      'taxonomy': instance.taxonomy,
      'parent': instance.parent,
      'meta': instance.meta,
      'links': instance.links,
    };

Tag _$TagFromJson(Map<String, dynamic> json) => Tag(
      id: (json['id'] as num).toInt(),
      count: (json['count'] as num?)?.toInt(),
      description: json['description'] as String?,
      link: json['link'] as String?,
      name: json['name'] as String?,
      slug: json['slug'] as String?,
      taxonomy: json['taxonomy'] as String?,
      meta: json['meta'] as List<dynamic>?,
      links: json['links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$TagToJson(Tag instance) => <String, dynamic>{
      'id': instance.id,
      'count': instance.count,
      'description': instance.description,
      'link': instance.link,
      'name': instance.name,
      'slug': instance.slug,
      'taxonomy': instance.taxonomy,
      'meta': instance.meta,
      'links': instance.links,
    };

Comment _$CommentFromJson(Map<String, dynamic> json) => Comment(
      id: (json['id'] as num).toInt(),
      post: (json['post'] as num?)?.toInt(),
      parent: (json['parent'] as num?)?.toInt(),
      author: (json['author'] as num?)?.toInt(),
      authorName: json['authorName'] as String?,
      authorEmail: json['authorEmail'] as String?,
      authorUrl: json['authorUrl'] as String?,
      authorIp: json['authorIp'] as String?,
      date: json['date'] as String?,
      dateGmt: json['dateGmt'] as String?,
      content: json['content'] as Map<String, dynamic>?,
      status: json['status'] as String?,
      type: json['type'] as String?,
      link: json['link'] as String?,
      meta: json['meta'] as Map<String, dynamic>?,
      links: json['links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$CommentToJson(Comment instance) => <String, dynamic>{
      'id': instance.id,
      'post': instance.post,
      'parent': instance.parent,
      'author': instance.author,
      'authorName': instance.authorName,
      'authorEmail': instance.authorEmail,
      'authorUrl': instance.authorUrl,
      'authorIp': instance.authorIp,
      'date': instance.date,
      'dateGmt': instance.dateGmt,
      'content': instance.content,
      'status': instance.status,
      'type': instance.type,
      'link': instance.link,
      'meta': instance.meta,
      'links': instance.links,
    };

Media _$MediaFromJson(Map<String, dynamic> json) => Media(
      id: (json['id'] as num).toInt(),
      date: json['date'] as String?,
      dateGmt: json['dateGmt'] as String?,
      guid: json['guid'] as Map<String, dynamic>?,
      modified: json['modified'] as String?,
      modifiedGmt: json['modifiedGmt'] as String?,
      slug: json['slug'] as String?,
      status: json['status'] as String?,
      type: json['type'] as String?,
      link: json['link'] as String?,
      title: json['title'] as Map<String, dynamic>?,
      author: (json['author'] as num?)?.toInt(),
      commentStatus: json['commentStatus'] as String?,
      pingStatus: json['pingStatus'] as String?,
      template: json['template'] as String?,
      meta: json['meta'] as Map<String, dynamic>?,
      description: json['description'] as Map<String, dynamic>?,
      caption: json['caption'] as Map<String, dynamic>?,
      altText: json['altText'] as String?,
      mediaType: json['mediaType'] as String?,
      mimeType: json['mimeType'] as String?,
      mediaDetails: json['mediaDetails'] as Map<String, dynamic>?,
      post: (json['post'] as num?)?.toInt(),
      sourceUrl: json['sourceUrl'] as String?,
      links: json['links'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$MediaToJson(Media instance) => <String, dynamic>{
      'id': instance.id,
      'date': instance.date,
      'dateGmt': instance.dateGmt,
      'guid': instance.guid,
      'modified': instance.modified,
      'modifiedGmt': instance.modifiedGmt,
      'slug': instance.slug,
      'status': instance.status,
      'type': instance.type,
      'link': instance.link,
      'title': instance.title,
      'author': instance.author,
      'commentStatus': instance.commentStatus,
      'pingStatus': instance.pingStatus,
      'template': instance.template,
      'meta': instance.meta,
      'description': instance.description,
      'caption': instance.caption,
      'altText': instance.altText,
      'mediaType': instance.mediaType,
      'mimeType': instance.mimeType,
      'mediaDetails': instance.mediaDetails,
      'post': instance.post,
      'sourceUrl': instance.sourceUrl,
      'links': instance.links,
    };
